sudo: required

language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install setuptools==18.5
  - pip install PyYAML
  - pip install cwltool
  - pip install cwl-runner

services:
  - docker

script:
  - test/test.sh

notifications:
  email: false
